#pragma once
constexpr int CHECK_NEW_WORLD = 12000;
constexpr int CHECK_MAP_PREVIEW = 12001;
void initOriginalModule();
void initFunctions();
void freeAll();

enum : unsigned int{
	MMAP_CHANGE_RESOURCES = 0U,
	MMAP_CHANGE_ALLIANCES,
	MMAP_CHANGE_PLAYER_COUNT,
	MMAP_HIDE_MAP_PREVIEW,
	MMAP_CHANGE_ECONOMY_MODE,
	MMAP_ADDON,
	MMAP_CONFLICT_MODE,
	MMAP_UNKNOWN_1,
	MMAP_UNKNOWN_2,
	MMAP_NEW_WORLD,
	MMAP_UNKNOWN_3,
	MMAP_UNKNOWN_4,
	MMAP_UNKNOWN_5,
	MMAP_UNKNOWN_6,
	MMAP_UNKNOWN_7,
	MMAP_UNKNOWN_8
};